name: C & GNU Make CI

on:
  push:
    branches: [ mit-licensed ]
  pull_request:
    branches: [ mit-licensed ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Create Build Directories
      run: mkdir -p build/{out,lib,examples}  
    - name: Make Library
      working-directory: ./src
      run: make all
    - name: Make Examples
      working-directory: ./examples
      run: make all
    - name: Install Dependencies for Tests
      run: sudo apt-get install check pkgconf
    - name: Build Tests
      working-directory: ./tests
      run: make all
    - name: Run Tests
      working-directory: ./build/tests
      run: |
        chmod +x expand
        ./expand
